version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pulseguard-postgres
    environment:
      POSTGRES_DB: retentiondb
      POSTGRES_USER: confluent_cdc
      POSTGRES_PASSWORD: confluent_cdc_password
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=5"
      - "-c"
      - "max_wal_senders=5"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U confluent_cdc -d retentiondb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
